import java.util.Scanner;

public class Main {
    public static void main(String[] args) {

        Scanner input = new Scanner(System.in);
        System.out.print("Enter first number- ");
        int user_input = input.nextInt(); // terima input

        // kena terima nombor 1 , 2 dan 3 sahaja
        // jadinya, selagi user masukkan input selain ini, kita keep
        // asking them to enter the number

        while (!(user_input == 1 || user_input == 2 || user_input == 3)) {
            System.out.print("Enter first number- ");
            user_input = input.nextInt(); // input baru sebab dia salah masuk nombor
            System.out.println("this is a " + user_input);
            if (user_input == 1 || user_input == 2 || user_input == 3) {
                break;
            }
        }

        // computer to generate random number by using Math.random, can use any other way u found.
        int min = 1;
        int max = 3;
        int computer_number = (int) Math.floor(Math.random() * (max - min + 1) + min);

        System.out.println("this is final user input :" + user_input);
        System.out.println("this is number generated by comp: " + computer_number);

        // so kita dah ada nombor from user dan computer. kita check values from these

        // comment untuk define setiap nombor mewakili apa.
        // 1 scissor, 2 paper, stone

        if (user_input == computer_number) {
            System.out.println("IT'S A TIE !");
        } else if (user_input == 1 && computer_number == 2) { // user = gunting, computer = paper, so user menang
            System.out.println("You've won!");
        } else if (user_input == 1 && computer_number == 3) {
            System.out.println("Computer menang. :P");
        }

    }
}